### ISSUE TITLE
Batch updates

### ISSUE THREAD

**Issue by rarkins** [fdesjardins/bunyan-postgres-stream#5]
Any support or plans to support batching of inserts to Postgres? I am using AWS RDS and concerned with hitting limits if sending lots of small logs.

**Comment by fdesjardins** [comment]
Unless bunyan or some plugin provides some sort of batching, no, it doesn't support it. I also hadn't planned anything, but it would be a good feature to add. I'd be happy to accept a PR if you want to take a shot at it.

**Comment by fdesjardins** [comment]
Yeah, I'm not seeing anything out there... Looks like [splunk-bunyan-logger](https://github.com/splunk/splunk-bunyan-logger) has a nice config for batching. Might be good to start with something similar.
