### ISSUE TITLE
Difficulties with cleanup/exit

### ISSUE THREAD

**Issue by rarkins** [fdesjardins/bunyan-postgres-stream#6]
If I call `stream.end()` once my app's work is done, I always get this error:
```
(node:10530) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: pool is draining and cannot accept work
```

If I add an artificial sleep before this `stream.end()` then it goes away, but I would prefer a deterministic way to ensure this.

The second problem is that my node.js script no longer exits once I've added this stream. I tried: `pgStream.end(process.exit);` but that's not helping.

I'm using a `pg` connection so I guess it's this line not doing its job somehow: `return this.pool.end(cb)`

**Comment by fdesjardins** [comment]
Interesting. Are you seeing the same behavior for the examples? Can you try [examples/simple.js](https://github.com/fdesjardins/bunyan-postgres-stream/blob/master/examples/simple.js) and see what happens?

I only get the `pool is draining` error if I try to log something after I've called `stream.end()`, but the not exiting thing is suspicious too, so I'm wondering if it's dependency version incompatibilities or something.

**Comment by rarkins** [comment]
The simple example runs and exist cleanly.

Although your example doesn't show a callback, it looks like `end` accepts one so I tried this:

```
  await sleep(5000);
  logger.info("Ending pg stream");
  pgStream.end(postEnd);
}

function postEnd() {
  console.log(process._getActiveHandles());
  console.log(process._getActiveRequests());
  process.exit();
}
```

Nothing is logged to console after `Ending pg stream`, so it seems the callback is not being called.

**Comment by rarkins** [comment]
Hi again,

I just did a test run emulating my production data and - for some reason - the postgres log stream died after 28 seconds and 1184 rows. I don't know why this was, but I'll probably stop using this streaming and instead write to file and batch `\copy` to postgres. I don't want you to take any more time troubleshooting this problem in case it was specific to my environment anyway. Thanks.

**Comment by fdesjardins** [comment]
Sounds good, thanks for the update. By the way, I just published a new version with some updated dependencies, including `pg`, so you might give that a go as well.
